# Generated by Django 2.1.1 on 2018-10-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='comment',
            field=models.CharField(blank=True, default='anything', max_length=50),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='talker',
            field=models.CharField(default='anything', max_length=20),
        ),
    ]
